name: CI

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build project
        run: mvn clean install

      - name: Run module and generate metrics file
        run: java -jar target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar src/test/resources/TestClass.java regex local target/generated_metrics csv

      - name: Compare metrics files
        run: diff src/test/resources/manual_metrics/manual_metrics.csv target/generated_metrics.csv
